<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Tests" duration-ms="9565" started-at="2014-04-04T21:05:38Z" finished-at="2014-04-04T21:05:48Z">
    <groups>
    </groups>
    <test name="Credit Card Test" duration-ms="9565" started-at="2014-04-04T21:05:38Z" finished-at="2014-04-04T21:05:48Z">
      <class name="com.github.tugu.SberbankTesting.tests.CreditCardTest">
        <test-method status="PASS" signature="init()" name="init" is-config="true" duration-ms="3874" started-at="2014-04-04T21:05:38Z" finished-at="2014-04-04T21:05:42Z">
        </test-method>
        <test-method status="FAIL" signature="testCreditCard()" name="testCreditCard" duration-ms="5635" started-at="2014-04-04T21:05:42Z" finished-at="2014-04-04T21:05:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Значение параметра 'Льготный период кредитования:' карты не совпадает expected:<50 дней> but was:<до 50 дней>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Значение параметра 'Льготный период кредитования:' карты не совпадает expected:<50 дней> but was:<до 50 дней>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at com.github.tugu.SberbankTesting.tests.CreditCardTest.testCreditCard(CreditCardTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1172)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="tearDown()" name="tearDown" is-config="true" duration-ms="47" started-at="2014-04-04T21:05:48Z" finished-at="2014-04-04T21:05:48Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
